const mongoose=require('mongoose');
const userSchema=mongoose.Schema({
    fullName:{
        type:String,
        trim:true,
        minLength:3,
        required:true
    },
    email:{
        type:String,
        unique:true,
        required:true
    },
    password:{
        type:String,
        unique:true,
        required:true
    },
    isOwner:{
        type:Boolean,
        default:false,
    },
    cart:[
        {
        type:mongoose.Schema.Types.ObjectId,
        ref:"product"
        }
    ],
    orders:{
        type:Array,
        default:[]
    }
});
module.exports=mongoose.model("user",userSchema);