const mongoose=require('mongoose');
const userSchema=mongoose.Schema({
    fullName:{
        type:String,
        trim:true,
        minLength:3,
        required:true
    },
    email:{
        type:String,
        unique:true,
        required:true
    },
    password:{
        type:String,
        unique:true,
        required:true
    },
    cart:{
        type:Array,
        default:[]
    },
    orders:{
        type:Array,
        default:[]
    },
    contact:Number,
    picture:String
});
module.exports=mongoose.model("user",userSchema);